// The item icons' pixel art (painted by icons.js). Each icon is a map of 16 rows of 16 characters, one per pixel: '.' is
// nothing, and every other character a colour from PALETTE, or from the icon's own `colors`. Leave a pixel's margin
// round the art: icons.js outlines everything in OUTLINE. Light comes from the top left.
//
// ICONS are keyed by `<kind>:<type>` (weapon:dagger), or by kind alone for one icon for every type (potion). An icon
// with `tint` has its pixels 1 to 5 (light to dark) shaded from the item's colour as it looks this run (Knowledge.color):
// one potion, wand, ring or key drawn for them all. A scroll has a rune from RUNES painted on it at RUNE_AT.
//
// A new item gets its icon by adding a map here under its key. Until it has one, it shows its glyph (KIND_GLYPH).

export const OUTLINE = '#170d07';

export const PALETTE = {
  '#': OUTLINE,
  W: '#ffffff',
  // steel
  A: '#e3e8ee', B: '#a8b1bc', C: '#727c89', D: '#474e59',
  // wood
  E: '#d09a5c', F: '#94633a', G: '#5f3e23',
  // leather
  H: '#b27b4b', I: '#7f5232', J: '#50331e',
  // gold
  K: '#fff2b0', L: '#f2c14f', M: '#c4892c', N: '#7c5216',
  // red
  P: '#ff8a8a', Q: '#d9263a', R: '#80101f',
  // parchment
  S: '#fbf2da', T: '#e0cc9e', U: '#ad9466',
  // glass
  V: '#eef7ff', X: '#a6bed0', Y: '#5e778a',
  // fire
  a: '#fff6c4', b: '#ffc948', c: '#ff8325', d: '#c43a12',
};

export const ICONS = {
  // --- Weapons: blade (or head) up to the right, hilt down to the left.
  'weapon:dagger': { map: [
    '................',
    '................',
    '............A...',
    '...........AC...',
    '..........WC....',
    '.........AC.....',
    '........AC......',
    '.......AC.......',
    '....LMAC........',
    '.....LM.........',
    '....HJLM........',
    '...HJ...........',
    '..MN............',
    '................',
    '................',
    '................',
  ] },
  'weapon:shortsword': { map: [
    '................',
    '.............A..',
    '............AC..',
    '...........AC...',
    '..........WC....',
    '.........AC.....',
    '........AC......',
    '...LM..AC.......',
    '....LMAC........',
    '.....LM.........',
    '....HJLM........',
    '...HJ..LM.......',
    '..HJ............',
    '.MN.............',
    '................',
    '................',
  ] },
  'weapon:longsword': { map: [
    '................',
    '.............A..',
    '...........ABC..',
    '..........ABC...',
    '.........WBC....',
    '........ABC.....',
    '.......ABC......',
    '...LM.ABC.......',
    '....LMBC........',
    '.....LM.........',
    '....HJLM........',
    '...HJ..LM.......',
    '..HJ............',
    '.QR.............',
    '................',
    '................',
  ] },
  'weapon:mace': { map: [
    '................',
    '...........B....',
    '..........ABB...',
    '.........AWBBC..',
    '........AABBCCC.',
    '.........BBCCD..',
    '........EGCCD...',
    '.......EG..D....',
    '......EG........',
    '.....EG.........',
    '....EG..........',
    '...HJ...........',
    '..HJ............',
    '.MN.............',
    '................',
    '................',
  ] },
  'weapon:spear': { map: [
    '................',
    '.............A..',
    '............AB..',
    '..........AABC..',
    '..........WBC...',
    '.........CD.....',
    '........EG......',
    '.......EG.......',
    '......EG........',
    '.....EG.........',
    '....EG..........',
    '...EG...........',
    '..EG............',
    '.FG.............',
    '................',
    '................',
  ] },
  'weapon:battleaxe': { map: [
    '................',
    '......AB.....EG.',
    '.....AABC...EG..',
    '....WABBCCDEG...',
    '....AABBCCDG....',
    '....ABBCCDG.....',
    '....ABC.EG......',
    '.....A.EG.......',
    '......EG........',
    '.....EG.........',
    '....EG..........',
    '...HJ...........',
    '..HJ............',
    '.MN.............',
    '................',
    '................',
  ] },
  'weapon:warhammer': { map: [
    '................',
    '.......ABC......',
    '........WBC.....',
    '.........ABC....',
    '..........ABC...',
    '.........EGABC..',
    '........EG..ABC.',
    '.......EG.......',
    '......EG........',
    '.....EG.........',
    '....EG..........',
    '...HJ...........',
    '..HJ............',
    '.MN.............',
    '................',
    '................',
  ] },

  // --- Off hand
  'offhand:lantern': { map: [
    '................',
    '......CCCC......',
    '.....C....C.....',
    '.....C.LM.C.....',
    '.....KLLLMN.....',
    '....KLLLLMMN....',
    '...KLLLLLMMMN...',
    '....DiiiiiiD....',
    '....DihhhhiD....',
    '....DhhgbhhD....',
    '....DhgbaghD....',
    '....DhgcbghD....',
    '....DhhMNhhD....',
    '...KLLLLLMMMN...',
    '....MMMMNNNN....',
    '................',
  ], colors: { g: '#ffd27a', h: '#d8883a', i: '#8c4c1c' } },

  // --- Shields
  'shield:wooden': { map: [
    '................',
    '......BBCC......',
    '....BBEEFGCC....',
    '...BFGEEFGEEC...',
    '..BEFGEEFGEEFC..',
    '..BEFGEEFGEEFC..',
    '.BEEFGEABGEEFGC.',
    '.BEEFGAWBCEEFGC.',
    '.BEEFGBBCDEEFGC.',
    '.BEEFGECDGEEFGC.',
    '..CEFGEEFGEEFD..',
    '..CEFGEEFGEEFD..',
    '...CFGEEFGEED...',
    '....CCEEFGDD....',
    '......CCDD......',
    '................',
  ] },

  // --- Armour: one tunic's shape, in leather, mail or plate.
  'armor:leather': { map: [
    '................',
    '...HHH....HHI...',
    '..HHHHH..HHHII..',
    '.HHHHHHIIHHHIII.',
    '.HHHHHHHHHHHIII.',
    '.HI.HHHHHHII.IJ.',
    '....HHHHHHII....',
    '....HHHHHHII....',
    '....JJJJMJJJ....',
    '....HHHHHHII....',
    '....HHHHHHII....',
    '....HHHHHIII....',
    '....IIIIIIJJ....',
    '................',
    '................',
    '................',
  ] },
  'armor:studded': { map: [
    '................',
    '...III....IIJ...',
    '..HIIII..IIIJJ..',
    '.HIIIIIJJIIIJJJ.',
    '.HIBIIIIIIIBJJJ.',
    '.HI.IIIIIIIJ.JJ.',
    '....IBIIIBIJ....',
    '....IIIIIIIJ....',
    '....JJJJMJJJ....',
    '....IBIIIBIJ....',
    '....IIIIIIIJ....',
    '....IBIIIBIJ....',
    '....JJJJJJJJ....',
    '................',
    '................',
    '................',
  ] },
  'armor:chain': { map: [
    '................',
    '...BCB....BCB...',
    '..ABCBC..CBCBD..',
    '.ABCBCBCBCBCBCD.',
    '.BCBCBCBCBCBCBD.',
    '.AB.CBCBCBCB.CD.',
    '....BCBCBCBC....',
    '....CBCBCBCB....',
    '....BCBCBCBC....',
    '....CBCBCBCB....',
    '....BCBCBCBC....',
    '....CBCBCBCD....',
    '....DDDDDDDD....',
    '................',
    '................',
    '................',
  ] },
  'armor:splint': { map: [
    '................',
    '...BBB....BBC...',
    '..ABBBB..BBBCC..',
    '.ABBBBBDDBBBBCD.',
    '.CCCCCCCCCCCCCD.',
    '.AB.DDDDDDDD.CD.',
    '....AAAAAAAB....',
    '....CCCCCCCD....',
    '....DDDDDDDD....',
    '....AAAAAAAB....',
    '....CCCCCCCD....',
    '....DDDDDDDD....',
    '....ABBBBBBC....',
    '................',
    '................',
    '................',
  ] },
  'armor:plate': { map: [
    '................',
    '...ABB....BCC...',
    '..AABBB..BBCCD..',
    '.AABBBBWBBBCCDD.',
    '.AABBBBWBBBCCDD.',
    '.AB.ABBWBBCC.DD.',
    '....ABBWBBCC....',
    '....ABBWBBCC....',
    '....ABBWBBCD....',
    '....DDDDDDDD....',
    '....ABBBBBCC....',
    '....DDDDDDDD....',
    '....ABBBBBCD....',
    '................',
    '................',
    '................',
  ] },

  // --- Potions: one flask, its liquid in the potion's colour.
  potion: { tint: true, map: [
    '................',
    '......EEEF......',
    '......FFGG......',
    '.......VX.......',
    '.......VY.......',
    '......VXXY......',
    '.....VXXXXY.....',
    '....V222222Y....',
    '...V12222223Y...',
    '...V22222233Y...',
    '...222222333Y...',
    '...2222333344...',
    '....33334444....',
    '.....444555.....',
    '................',
    '................',
  ] },

  // --- Scrolls: one open scroll, with the rune for its label on it (RUNES).
  scroll: { map: [
    '................',
    '.TSSSSSSSSSSSSU.',
    '.UTTTTTTTTTTTUU.',
    '..############..',
    '..SSSSSSSSSSST..',
    '..SSSSSSSSSSST..',
    '..SSSSSSSSSSST..',
    '..SSSSSSSSSSTT..',
    '..SSSSSSSSSSTT..',
    '..SSSSSSSSSSTT..',
    '..TSSSSSSSSSTT..',
    '..TTTTTTTTTTTU..',
    '..############..',
    '.TSSSSSSSSSSSSU.',
    '.UTTTTTTTTTTTUU.',
    '................',
  ] },

  // --- Wands: one wand, its shaft in the wand's wood or metal.
  wand: { tint: true, map: [
    '................',
    '............VX..',
    '...........VWVX.',
    '...........XVXY.',
    '..........LMXY..',
    '.........MN.....',
    '........24......',
    '.......24.......',
    '......34........',
    '.....24.........',
    '....24..........',
    '...24...........',
    '..LM............',
    '.MN.............',
    '................',
    '................',
  ] },

  // --- Rings: one gold ring, its stone in the ring's gem.
  ring: { tint: true, map: [
    '................',
    '................',
    '......1122......',
    '.....112233.....',
    '.....123344.....',
    '....LM3445MN....',
    '...LKM....MMN...',
    '..LK........MN..',
    '..LL........MN..',
    '..LL........NN..',
    '..ML........NN..',
    '...MMM....NNN...',
    '....MMNNNNNN....',
    '................',
    '................',
    '................',
  ] },

  // --- Food
  'food:ration': { map: [
    '................',
    '................',
    '................',
    '....HHHHHHHH....',
    '...HHHHTHHHHI...',
    '..HHHHHTHHHHII..',
    '..HHHHUTUHHHII..',
    '..TTTTTTTTTTTU..',
    '..HHHHUTUHHIII..',
    '..HHHHHTHHHIII..',
    '..IIIIITIIIIJJ..',
    '...IIIITIIIJJ...',
    '....JJJJJJJJ....',
    '................',
    '................',
    '................',
  ], colors: { T: '#d8c490', U: '#8f7a52' } },
  'food:apple': { map: [
    '................',
    '.........gg.....',
    '........Ggh.....',
    '....oop.Gpqq....',
    '...ooooppppqq...',
    '...oWopppppqq...',
    '...ooppppppqq...',
    '...oppppppqqq...',
    '...pprppppqqr...',
    '...ppppppqqqr...',
    '....pppqqqqr....',
    '.....pqqqrr.....',
    '......qrr.......',
    '................',
    '................',
    '................',
  ], colors: { o: '#c8704f', p: '#9a4431', q: '#6c2c20', r: '#45190f', g: '#8d9a46', h: '#5c6a2a' } },

  // --- Artefacts
  'artefact:chalice': { map: [
    '................',
    '................',
    '....KLLLLLLM....',
    '...LRPQQQQRRM...',
    '...LLRRRRRRMM...',
    '...KLLLLLLMMN...',
    '....LLLLLMMN....',
    '.....LLLMMN.....',
    '.......LM.......',
    '......QLMR......',
    '.......LM.......',
    '.....KLLMMN.....',
    '....LLLLMMMN....',
    '................',
    '................',
    '................',
  ] },
  'artefact:eye': { map: [
    '................',
    '................',
    '......effg......',
    '....eeffffgg....',
    '...eWffggggghh..',
    '...effgiiiggh...',
    '..effgikkiggh...',
    '..effgikkkighh..',
    '..fffgiikiighh..',
    '...ffggiiigghh..',
    '...fgggggghhh...',
    '....gggghhhh....',
    '......hhhh......',
    '................',
    '................',
    '................',
  ], colors: { e: '#c8fff6', f: '#5fe3cf', g: '#26a794', h: '#146458', i: '#b6fbff', k: '#041a17' } },
  'artefact:horn': { map: [
    '................',
    '...........KLL..',
    '..........K##LM.',
    '.........LL#LMN.',
    '........STLLMN..',
    '.......STTTU....',
    '......STTTU.....',
    '.....STTTU......',
    '....LLMN........',
    '....STU.........',
    '...STU..........',
    '...TU...........',
    '..TU............',
    '..U.............',
    '................',
    '................',
  ] },
  'artefact:cloak': { map: [
    '................',
    '......cccc......',
    '.....cccddd.....',
    '....ccekkedd....',
    '....cekkkked....',
    '....cekkkkde....',
    '...ccdekkedde...',
    '...cccdeedddd...',
    '..ccccdLMddddd..',
    '..cccccddddddd..',
    '..ccccdddddddf..',
    '.cccccdddddddff.',
    '.ccccdddddddfff.',
    '.cdcdcdcdcdfdff.',
    '................',
    '................',
  ], colors: { c: '#7a7aa6', d: '#4e4e72', e: '#2e2e48', f: '#25253a', k: '#0c0c14' } },
  'artefact:boots': { map: [
    '................',
    '................',
    '.....cccccd.....',
    '..aa.cbbbbd.....',
    '.abbacddddde....',
    '..abbcddddde....',
    '...abcddddde....',
    '.....cddddde....',
    '.....cddddde....',
    '.....cddddddee..',
    '.....cdddddddde.',
    '.....cddddddddd.',
    '.....eeeeeeeeee.',
    '................',
    '................',
    '................',
  ], colors: { a: '#ffffff', b: '#d8ecf8', c: '#a8d4ee', d: '#6a9ec4', e: '#3c5a78' } },

  'artefact:ember': { map: [
    '................',
    '................',
    '...cc....cc.....',
    '..cbbc..cbbd....',
    '.cbaabccbbbcd...',
    '.cbaabbbbbccd...',
    '.cbbbbbbbccdd...',
    '..cbbbbbbccd....',
    '...cbbbbccd.....',
    '....cbbccd......',
    '.....cccd.......',
    '......cd........',
    '................',
    '................',
    '................',
    '................',
  ] },
  // --- The Amulet of Yendor
  'amulet:yendor': { map: [
    '................',
    '.....LLLLLL.....',
    '....L......M....',
    '...L........M...',
    '...L........N...',
    '....M......N....',
    '.....MN..MN.....',
    '......KLLM......',
    '.....KLQQLM.....',
    '....KLQPQQLM....',
    '....LLQQQRLN....',
    '....MLQQRRMN....',
    '.....MLRRMN.....',
    '......MNNN......',
    '................',
    '................',
  ] },

  // --- Gold and keys
  gold: { map: [
    '................',
    '................',
    '................',
    '....KLLM........',
    '...KLLLLM.......',
    '...LLLLMN.......',
    '...NMMMNN.KLLM..',
    '...LLLMMNKLLLLM.',
    '...NMMMNNLLLLMN.',
    '...LLLMMNNMMMNN.',
    '..KLLMNNNLLLMMN.',
    '.KLLLLMNNNMMMNN.',
    '.LLLLMNLLLMMMN..',
    '.MMMNN..NNNNN...',
    '................',
    '................',
  ] },
  key: { tint: true, map: [
    '................',
    '................',
    '...1223.........',
    '..12..34........',
    '..2....4........',
    '..2....4........',
    '..23..45........',
    '...3445.........',
    '......34........',
    '.......34.......',
    '........34......',
    '.........34.....',
    '.........534....',
    '..........5.34..',
    '...........534..',
    '................',
  ] },

  // --- Pack expansions
  'container:scroll_holder': { map: [
    '................',
    '....ST..ST......',
    '....TU..TU.ST...',
    '...HHHHHHHHTU...',
    '...HIIIIIIIHH...',
    '...HHHHHHHHHI...',
    '...HHHHHHHHII...',
    '...HHHHHHHHII...',
    '...JMMJJJJJJJ...',
    '...HHHHHHHHII...',
    '...HHHHHHHHII...',
    '...HHHHHHHIII...',
    '...JMMJJJJJJJ...',
    '...IIIIIIIIJJ...',
    '................',
    '................',
  ] },
  'container:potion_bandolier': { map: [
    '................',
    '................',
    '...E...E...E....',
    '...V...V...V....',
    '..VxY.VuY.VoY...',
    '..xxy.uuv.oop...',
    '.HHHHHHHHHHHHHI.',
    '.IMIIIIMIIIIMIJ.',
    '.JJJJJJJJJJJJJJ.',
    '..xyy.uvv.opp...',
    '..yyY.vvY.ppY...',
    '................',
    '................',
    '................',
    '................',
    '................',
  ], colors: { x: '#ff6a7a', y: '#b0283a', u: '#6ac8ff', v: '#2a78c0', o: '#9ee06a', p: '#4a9a30' } },
  'container:wand_holster': { map: [
    '................',
    '......V...X.....',
    '......E...F.....',
    '......F..FG.....',
    '.....HHHHHHH....',
    '.....HIIIIIIJ...',
    '.....HHHHHHII...',
    '.....HHHHHHII...',
    '.....HHHHHIII...',
    '.....JMJJJJJJ...',
    '.....HHHHHIII...',
    '......HHHHII....',
    '.......HHII.....',
    '........IJ......',
    '................',
    '................',
  ] },
  'container:bullet_pouch': { map: [
    '................',
    '................',
    '......U..U......',
    '.......UU.......',
    '.....HHHHHH.....',
    '......JJJJ......',
    '.....HHHHHII....',
    '....HHHHHHHII...',
    '...HHHHHHHHIII..',
    '...HHHHHHHHIII..',
    '...HHHHHHHIIIJ..',
    '...IHHHHHIIIJJ..',
    '....IIIIIIIJJ...',
    '......JJJJJ.....',
    '................',
    '................',
  ], colors: { U: '#c8b080' } },
};

// Runes for the scrolls, 5 across and 6 down, painted in RUNE_INK at RUNE_AT on the scroll: each kind of scroll is
// given one each run (Knowledge.rune). There are more than kinds of scroll, to leave room for new ones.
export const RUNE_AT = [5, 5];
export const RUNE_INK = '#5a1c12';
export const RUNES = [
  ['..x..', '.xxx.', 'x.x.x', '..x..', '..x..', '..x..'],
  ['x.x.x', '.xxx.', '..x..', '..x..', '..x..', '..x..'],
  ['..x..', '.x.x.', 'x...x', '.x.x.', '..x..', '.x.x.'],
  ['x...x', 'xx.xx', 'x.x.x', 'x.x.x', 'xx.xx', 'x...x'],
  ['x...x', '.x.x.', '..x..', '..x..', '.x.x.', 'x...x'],
  ['...x.', '..x..', '.xxx.', '...x.', '..x..', '.x...'],
  ['x....', 'xx...', 'x.x..', 'x.x..', 'xx...', 'x....'],
  ['xxx..', 'x..x.', 'xxx..', 'x.x..', 'x..x.', 'x...x'],
  ['...x.', '..x..', '.x...', '.x...', '..x..', '...x.'],
  ['x...x', 'x...x', 'xx..x', 'x.x.x', 'x..xx', 'x...x'],
  ['..x..', 'x.x..', '.xx..', '..xx.', '..x.x', '..x..'],
  ['xx...', 'x.x..', 'x..x.', 'x....', 'x....', 'x....'],
  ['xx...', 'x.x..', 'xx...', 'xx...', 'x.x..', 'xx...'],
  ['.....', '.xxx.', 'x...x', 'x.x.x', 'x...x', '.xxx.'],
  ['..xx.', '..x..', '..x..', '..x..', '..x..', '.xx..'],
  ['xx...', 'x.x..', 'xx...', 'x....', 'x....', 'x....'],
];

// The marks in the corners of pack tiles (MARKS in tiles.js), for what a thing does: 9 rows of 9, the same way.
export const MARK_ICONS = {
  fire: { map: ['.........', '....c....', '...cb....', '...cbc...', '..cbabc..', '..cbaac..', '..cbaac..', '...ccc...', '.........'] },
  ice: { map: ['.........', '....i....', '..i.i.i..', '...iji...', '.iijWjii.', '...iji...', '..i.i.i..', '....i....', '.........'], colors: { i: '#9fdcff', j: '#e2f6ff' } },
  lightning: { map: ['.........', '.....yy..', '....yy...', '...yyyy..', '....yy...', '...yy....', '...y.....', '..y......', '.........'], colors: { y: '#ffe04a' } },
  poison: { map: ['.........', '....g....', '...ggg...', '..gghgg..', '..gWggg..', '..ggggh..', '..gghhh..', '...hhh...', '.........'], colors: { g: '#6ad850', h: '#2f8a2a' } },
  magic: { map: ['.........', '....v....', '....v....', '...vwv...', '.vvwWwvv.', '...vwv...', '....v....', '....v....', '.........'], colors: { v: '#9a5cff', w: '#d8b8ff' } },
  heal: { map: ['.........', '..rr.rr..', '.rPrrrrr.', '.rrrrrrq.', '.rrrrrrq.', '..rrrrq..', '...rrq...', '....q....', '.........'], colors: { r: '#e8364a', q: '#9c1a2a' } },
  strength: { map: ['.........', '..oooo...', '.opopopo.', '.opopopo.', '.ooooooo.', '.oppppq..', '.ooopq...', '..oooq...', '.........'], colors: { o: '#f0a848', p: '#b86a22', q: '#8a4a14' } },
  experience: { map: ['.........', '....y....', '...yky...', '.yyykyyy.', '..yyyyy..', '..yyzyy..', '.yyz.zyy.', '.yz...zy.', '.........'], colors: { y: '#f4c440', k: '#fff2b0', z: '#b4841c' } },
  haste: { map: ['.........', '.t..t....', '..t..t...', '...t..t..', '....t..t.', '...t..t..', '..t..t...', '.t..t....', '.........'], colors: { t: '#5ee0d0' } },
  mind: { map: ['.........', '.........', '..vvvvv..', '.vwwiwwv.', '.vwikiwv.', '.vwwiwwv.', '..vvvvv..', '.........', '.........'], colors: { v: '#a47cff', w: '#ece4ff', i: '#b890ff', k: '#2a1a4a' } },
  confusion: { map: ['.........', '..pppp...', '.p....p..', '.p.pp.p..', '.p.p..p..', '.p..pp...', '..p......', '...ppppp.', '.........'], colors: { p: '#e070e0' } },
  darkness: { map: ['.........', '...mmm...', '..mm.....', '.mm......', '.mm......', '.mm......', '..mm.....', '...mmm...', '.........'], colors: { m: '#8a8ab8' } },
  paralysis: { map: ['.........', '.zzzzz...', '....z....', '...z.....', '..z......', '.zzzzz...', '.....zzz.', '......z..', '.........'], colors: { z: '#a8c8ff' } },
  identify: { map: ['.........', '..www....', '.w...w...', '.w.V.w...', '.w...w...', '..www....', '.....ss..', '......ss.', '.........'], colors: { w: '#e8dcb0', s: '#a08050' } },
  upgrade: { map: ['.........', '....u....', '...uuu...', '..uuuuu..', '.uuuuuuu.', '...uuu...', '...uuu...', '...uuu...', '.........'], colors: { u: '#6aa8ff' } },
  cleanse: { map: ['.........', '....k....', '.k..k..k.', '..k.k.k..', '.kkkWkkk.', '..k.k.k..', '.k..k..k.', '....k....', '.........'], colors: { k: '#fff0b8' } },
  teleport: { map: ['.........', '...ppp...', '..p...p..', '.p..q..p.', '.p.qWq.p.', '.p..q..p.', '..p...p..', '...ppp...', '.........'], colors: { p: '#9a58ff', q: '#d8b8ff' } },
  map: { map: ['.........', '.sssssss.', '.s..s..s.', '.s..s..s.', '.ssss.ss.', '.s.....s.', '.s..s..s.', '.sssssss.', '.........'], colors: { s: '#d8b070' } },
  aggravate: { map: ['.........', '....r....', '...rrr...', '...rrr...', '...rrr...', '....r....', '.........', '....r....', '.........'], colors: { r: '#ff5a3a' } },
  fear: { map: ['.........', '..sssss..', '.sssssss.', '.s#sss#s.', '.s#sss#s.', '.ssss#ss.', '..sssss..', '..s.s.s..', '.........'], colors: { s: '#e8e4b8' } },
  summon: { map: ['.........', '.r.....r.', '.rr...rr.', '..rrrrr..', '..ryryr..', '..rrrrr..', '...rqr...', '....r....', '.........'], colors: { r: '#e84830', q: '#8a1a10', y: '#ffe04a' } },
  recharge: { map: ['.........', '......k..', '.....kWk.', '....y.k..', '...y.....', '..y......', '.y.......', '.........', '.........'], colors: { y: '#c89a50', k: '#ffd040' } },
  enchant: { map: ['.........', '.........', '....y....', '...yky...', '.yykWkyy.', '...yky...', '....y....', '.........', '.........'], colors: { y: '#f4c860', k: '#fff2b0' } },
  protection: { map: ['.........', '.sssssss.', '.sWsssst.', '.sssssst.', '.sssssst.', '..sssst..', '...sst...', '....t....', '.........'], colors: { s: '#c8d0dc', t: '#7c8898' } },
  food: { map: ['.........', '....bbb..', '...bbbbb.', '...bbbbc.', '....bbc..', '...w.....', '..ww.....', '.w.......', '.........'], colors: { b: '#c8783a', c: '#8a4a1e', w: '#f0e8d8' } },
  quiet: { map: ['.........', '......ww.', '.....wgw.', '....wgw..', '...wgw...', '..wgw....', '..g......', '.g.......', '.........'], colors: { w: '#dde4ee', g: '#8894a4' } },
  steady: { map: ['.........', '...aaa...', '...a.a...', '....a....', '..aaaaa..', '....a....', '.a..a..a.', '..aaaaa..', '.........'], colors: { a: '#a8bcd4' } },
  thorns: { map: ['.........', '...t.t...', '...t.t...', '..tt.tt..', '..tt.tt..', '.ttttttt.', '.uuuuuuu.', '.........', '.........'], colors: { t: '#e0dcc0', u: '#8a4a2a' } },
};
